services:
  backend:
    image: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: flask run -h 0.0.0.0
    environment:
      - DATABASE_URI=sqlite:////db/api.db
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
